CREATE TABLE IMR_DETAIL_DATA(
	PCOM_ID VARCHAR(30) NOT NULL,
	DATA_ID VARCHAR(30) NOT NULL,
	TYPE CHAR(2) NOT NULL,
	DATE1 CHAR(8),
	FILE_NAME VARCHAR(100),
	DOWNLOAD_PATH VARCHAR(100),
	FILE_KEY VARCHAR(64),
	STATUS CHAR(2),
	CRT_TIME VARCHAR(16),
	UP_TIME VARCHAR(16)
)IN "TD_SALE" INDEX IN "TD_OTHER_IDX" ;
ALTER TABLE "IMR_DETAIL_DATA" ADD CONSTRAINT "IMR_DETAIL_DATA_PK"
		PRIMARY KEY("PCOM_ID", "DATA_ID","TYPE");

CREATE TABLE IMR_DETAIL_DATA_LOG(
	PCOM_ID VARCHAR(30) NOT NULL,
	DATA_ID VARCHAR(30) NOT NULL,
	LOG_ID VARCHAR(30) NOT NULL,
	STATUS CHAR(2),
	IS_SUCCESS CHAR(1),
	NOTE VARCHAR(255),
	UP_TIME VARCHAR(16)
)IN "TD_SALE" INDEX IN "TD_OTHER_IDX" ;
ALTER TABLE "IMR_DETAIL_DATA_LOG" ADD CONSTRAINT "IMR_DETAIL_DATA_LOG_PK"
		PRIMARY KEY("PCOM_ID", "DATA_ID","LOG_ID");