ALTER TABLE ICA_CO_LINE ADD QTY_ARE  DECIMAL(18,6) DEFAULT 0 ;

ALTER TABLE ICA_CO_ALLOT DROP(FACT_ID);
ALTER TABLE ICA_CO_ALLOT ADD WHSE_ID VARCHAR(30) DEFAULT ' ' NOT NULL;

ALTER TABLE ICA_CO_ALLOT_LINE DROP (FACT_ID);
ALTER TABLE ICA_CO_ALLOT_LINE ADD WHSE_ID VARCHAR(30) DEFAULT ' ' NOT NULL;


CREATE TABLE ICA_COM_ITEM_MONTH(
	DATE1 CHAR(6) NOT NULL,
	ICOM_ID VARCHAR(30) NOT NULL,
	COM_ID VARCHAR(30) NOT NULL,
	ITEM_ID VARCHAR(30) NOT NULL,
	GRADE_ID VARCHAR(30) NOT NULL,
	SALE_CENTER_ID  VARCHAR(30) ,
	SALEORG_ID  VARCHAR(30) ,
	AREA_ID  VARCHAR(30) ,
	SLSMAN_ID  VARCHAR(30) ,
	QTY_SOLD DECIMAL(18,2)
)TABLESPACE "TD_SALE";
ALTER TABLE  "ICA_COM_ITEM_MONTH" 
	ADD CONSTRAINT ICA_COM_ITEM_MONTH_PK PRIMARY KEY
		("DATE1","ICOM_ID","COM_ID","ITEM_ID","GRADE_ID") USING INDEX TABLESPACE "TD_OTHER_IDX";