--各个指标说明：
--库存=月末库存剩余量
--存销比=库存/本月销量 
--断货户数=本月有需求量没有订购量的零售户数 
--零售户断货率=断货户数/本月有需求量的户数
--箱=X（查询的数据）*条支比率/箱支比率
SELECT 
	A.ORGAN_NAME, --大区
	A.SALEORG_ID,
	A.COM_SHORT_NAME, --商业公司简称
	A.COM_ID,
	X_SIZE,--箱支比率
	T_SIZE,--条支比率
	QTY_ORD,        --本月零售户订购量
	CUST_COUNT_NEED,        --本月有需求户数
	CUST_COUNT_ORD,        --本月订购户数
	QTY_PURCH,        --本月购进量
	QTY_EOM,        --月末库存量
	QTY_ORD_LAST,        --上月零售户订购量
	CUST_COUNT_NEED_LAST,        --上月有需求户数
	CUST_COUNT_ORD_LAST,        --上月订购户数
	QTY_PURCH_LAST,        --上月购进量
	QTY_EOM_LAST        --上月月末库存量
FROM
	(
		SELECT 
			PO.ORGAN_NAME, 
			IC.SALEORG_ID,
			IC.COM_SHORT_NAME, 
			IC.COM_ID
		FROM 
			ICA_COM IC,
			PUB_ORGAN PO
		WHERE 
			IC.ICOM_ID='SD0000000000001' 
			AND IC.STATUS = '01' 
			AND IC.SALEORG_ID=PO.ORGAN_ID 
			AND PO.IN_USE='1'
	)A LEFT JOIN 
	(
		SELECT
			A.COM_ID,
			D.X_SIZE,
			C.T_SIZE,
			SUM(CASE WHEN B.DATE1='201609' THEN QTY_ORD ELSE 0 END) QTY_ORD,        --本月零售户订购量
			SUM(CASE WHEN B.DATE1='201609' THEN CUST_COUNT_NEED ELSE 0 END) CUST_COUNT_NEED,        --本月有需求户数
			SUM(CASE WHEN B.DATE1='201609' THEN CUST_COUNT_ORD ELSE 0 END) CUST_COUNT_ORD,        --本月订购户数
			SUM(CASE WHEN C.DATE1='201609' THEN QTY_PURCH ELSE 0 END) QTY_PURCH,        --本月购进
			SUM(CASE WHEN C.DATE1='201609' THEN QTY_EOM ELSE 0 END) QTY_EOM,        --月末库存量
			SUM(CASE WHEN B.DATE1='201608' THEN QTY_ORD ELSE 0 END) QTY_ORD_LAST,        --上月零售户订购量
			SUM(CASE WHEN B.DATE1='201608' THEN CUST_COUNT_NEED ELSE 0 END) CUST_COUNT_NEED_LAST,        --上月有需求户数
			SUM(CASE WHEN B.DATE1='201608' THEN CUST_COUNT_ORD ELSE 0 END) CUST_COUNT_ORD_LAST,        --上月订购户数
			SUM(CASE WHEN C.DATE1='201608' THEN QTY_PURCH ELSE 0 END) QTY_PURCH_LAST,        --上月购进
			SUM(CASE WHEN C.DATE1='201608' THEN QTY_EOM ELSE 0 END) QTY_EOM_LAST        --上月月末库存量
		FROM
			ICA_COM A,
			SCMR_PI_ITEM_ORD_MONTH B,
			SCMR_PI_ITEM_STOCK_MONTH C,
			ICA_ITEM D
		WHERE 
			B.DATE1=C.DATE1 
			AND B.DATE1 BETWEEN '201608' AND '201609'
			AND A.COM_ID=B.CCOM_ID 
			AND A.COM_ID=C.CCOM_ID
			AND B.PACK_BAR='6901028148603' 
			AND B.PACK_BAR=C.PACK_BAR 
			AND B.PACK_BAR=D.PACK_BAR 
			AND A.ICOM_ID='SD0000000000001' 
			AND A.STATUS = '01' 
		GROUP BY  
			A.COM_ID,
			D.X_SIZE,
			C.T_SIZE
	)B ON A.COM_ID=B.COM_ID 
ORDER BY 
	A.SALEORG_ID,
	QTY_ORD
