--各个指标说明：
--库存=月末库存剩余量
--存销比=库存/本月销量 
--断货户数=本月有需求量没有订购量的零售户数 
--零售户断货率=断货户数/本月有需求量的户数
--箱=X（查询的数据）*条支比率/箱支比率

SELECT
	A.ITEM_NAME--商品名称
	,A.PACK_BAR--条包条形码
	,A.X_SIZE--箱支比率
	,SS.T_SIZE,--条支比率
	SUM(CASE WHEN SO.DATE1='201609' THEN QTY_ORD ELSE 0 END) QTY_ORD,        --本月零售户订购量
	SUM(CASE WHEN SO.DATE1='201609' THEN CUST_COUNT_NEED ELSE 0 END) CUST_COUNT_NEED,        --本月有需求户数
	SUM(CASE WHEN SO.DATE1='201609' THEN CUST_COUNT_ORD ELSE 0 END) CUST_COUNT_ORD,        --本月订购户数
	SUM(CASE WHEN SS.DATE1='201609' THEN QTY_PURCH ELSE 0 END) QTY_PURCH,        --本月购进
	SUM(CASE WHEN SS.DATE1='201609' THEN QTY_EOM ELSE 0 END) QTY_EOM,        --月末库存量
	SUM(CASE WHEN SO.DATE1='201608' THEN QTY_ORD ELSE 0 END) QTY_ORD_LAST,        --上月零售户订购量
	SUM(CASE WHEN SO.DATE1='201608' THEN CUST_COUNT_NEED ELSE 0 END) CUST_COUNT_NEED_LAST,        --上月有需求户数
	SUM(CASE WHEN SO.DATE1='201608' THEN CUST_COUNT_ORD ELSE 0 END) CUST_COUNT_ORD_LAST,        --上月订购户数
	SUM(CASE WHEN SS.DATE1='201608' THEN QTY_PURCH ELSE 0 END) QTY_PURCH_LAST,        --上月购进
	SUM(CASE WHEN SS.DATE1='201608' THEN QTY_EOM ELSE 0 END) QTY_EOM_LAST        --上月月末库存量
FROM
	ICA_ITEM A , 
	SCMR_PI_ITEM_ORD_MONTH SO,
	SCMR_PI_ITEM_STOCK_MONTH SS
WHERE 
	SO.DATE1=SS.DATE1 
	AND SO.DATE1 BETWEEN '201608' AND '201609'
	AND A.PACK_BAR=SO.PACK_BAR AND A.PACK_BAR=SS.PACK_BAR
	AND ICOM_ID='SD0000000000001'
	AND IS_USE='1' 
GROUP BY 
	A.ITEM_NAME,
	A.PACK_BAR,
	A.X_SIZE,
	SS.T_SIZE
