
# INSERT INTO DB2INST1.SCMR_PI_ITEM_ORD_MONTH
# (PCOM_ID, CCOM_ID, COM_ID, PACK_BAR, T_SIZE, ITEM_ID, DATE1, CUST_COUNT_NORMAL, CUST_COUNT_NEED, CO_COUNT_NEED, QTY_NEED, CUST_COUNT_ORD, CO_COUNT_ORD, QTY_ORD, AMT_ORD, CUST_COUNT_NEED_MANY, QTY_NEED_NEED_MANY, QTY_ORD_NEED_MANY, AMT_ORD_NEED_MANY, CUST_COUNT_ORD_MANY, QTY_NEED_ORD_MANY, QTY_ORD_ORD_MANY, AMT_ORD_ORD_MANY, CUST_COUNT_ORD_EVERY, QTY_NEED_ORD_EVERY, QTY_ORD_ORD_EVERY, AMT_ORD_ORD_EVERY, UPDATE_TIME)
# VALUES('000000000004294', '000000000000138', '630000000', '6901028149242', 200, '31010101', '201609', 14, 5, 34, 34.00, 34, 12, 99.00, 345245.00, 0, #{parseInt(Math.random()*100)}, #{parseInt(Math.random()*100)}, #{parseInt(Math.random()*100)}, 0, #{parseInt(Math.random()*100)}, #{parseInt(Math.random()*10)0}, #{parseInt(Math.random()*100)}, 0, #{parseInt(Math.random()*100)}, #{parseInt(Math.random()*100)}, #{parseInt(Math.random()*100)}, TO_DATE('2016-09-23 09:55:47','YYYY-MM-DD HH24:MI:SS'));
fs = require('fs');
bussForms = [
	'COM_EMERGE_VERIFY_UPDATE',
	'IND_EMERGE_DETAIL',
	'IND_EMERGE_INSERT',
	'IND_EMERGE_SUBVERIFY_DETAIL',
	'IND_EMERGE_SUBVERIFY_UPDATE',
	'IND_EMERGE_UPDATE',
	'IND_EMERGE_VERIFY_UPDATE',
	'MODIFY_DETAIL',
	'MODIFY_UPDATE',
	'SALE_RATE_SUBVERIFY_UPDATE',
	'SALE_RATE_VERIFY_UPDATE'
]
rlt = ''
for bussForm in bussForms
	rlt += ( """

		DELETE FROM ICA_DIST_LISTCONFI WHERE ICOM_ID='20530001' AND BUSS_FORM='#{bussForm}' AND KEY_NAME='CURR_QTY_TRANS_DISPLAY';

		INSERT INTO ICA_DIST_LISTCONFI
		(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
		VALUES('20530001', '#{bussForm}', 'CURR_QTY_TRANS_DISPLAY#CURR_QTY_NOT_DECOMP#CURR_QTY_NOT_SIGN#CURR_QTY_CONTRACT#CURR_QTY_TODAY_CON', '在途量', 190.00000, '1', '1', '0', '1');

		INSERT INTO ICA_DIST_LISTCONFI
		(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
		VALUES('20530001', '#{bussForm}', 'CURR_QTY_TRANS_DISPLAY', '合计', 190.100000, '0', '1', '0', '0');

		INSERT INTO ICA_DIST_LISTCONFI
		(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
		VALUES('20530001', '#{bussForm}', 'CURR_QTY_NOT_DECOMP', '未分解配货单', 190.200000, '0', '1', '0', '0');

		INSERT INTO ICA_DIST_LISTCONFI
		(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
		VALUES('20530001', '#{bussForm}', 'CURR_QTY_NOT_SIGN', '未签章合同', 190.300000, '0', '1', '0', '0');

		INSERT INTO ICA_DIST_LISTCONFI
		(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
		VALUES('20530001', '#{bussForm}', 'CURR_QTY_CONTRACT', '已鉴章未入库合同', 190.400000, '0', '1', '0', '0');

		INSERT INTO ICA_DIST_LISTCONFI
		(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
		VALUES('20530001', '#{bussForm}', 'CURR_QTY_TODAY_CON', '今日入库合同', 190.500000, '0', '1', '0', '0');

	""")

resultBuffer = new Buffer(rlt)
fs.writeFile('./lala.sql',resultBuffer,(err)->
		if err
			throw err
		console.log('has finished')
	)