
SELECT
	COUNT(1) DATA_RECEIVE_COUNT,
	'SCMR_SGP_ORG_CUSTTYPE_ITEM_SW' TABLE_NAME,
	A.PCOM_ID
FROM
	SCMR_SGP_ORG_CUSTTYPE_ITEM_SW A,
	SCMR_RECEIVE_LOG B
WHERE
	A.DATE1 BETWEEN B.DATA_DATE_START AND B.DATA_DATE_END
	AND A.PCOM_ID=B.PCOM_ID
	AND B.TABLE_NAME='SCMR_SGP_ORG_CUSTTYPE_ITEM_SW'
	AND B.RECEIVE_DATE='${value}'
GROUP BY
	A.PCOM_ID

UNION ALL

SELECT
	COUNT(1) DATA_RECEIVE_COUNT,
	'SCMR_PI_COM_DAY' TABLE_NAME,
	A.PCOM_ID
FROM
	SCMR_PI_COM_DAY A,
	SCMR_RECEIVE_LOG B
WHERE
	A.DATE1 BETWEEN B.DATA_DATE_START AND B.DATA_DATE_END
	AND A.PCOM_ID=B.PCOM_ID
	AND B.TABLE_NAME='SCMR_PI_COM_DAY'
	AND B.RECEIVE_DATE='${value}'
GROUP BY
	A.PCOM_ID

UNION ALL

SELECT
	COUNT(1) DATA_RECEIVE_COUNT,
	'SCMR_SGP_COM_CUSTTYPE_ITEM_SW' TABLE_NAME,
	A.PCOM_ID
FROM
	SCMR_SGP_COM_CUSTTYPE_ITEM_SW A,
	SCMR_RECEIVE_LOG B
WHERE
	A.DATE1 BETWEEN B.DATA_DATE_START AND B.DATA_DATE_END
	AND A.PCOM_ID=B.PCOM_ID
	AND B.TABLE_NAME='SCMR_SGP_COM_CUSTTYPE_ITEM_SW'
	AND B.RECEIVE_DATE='${value}'
GROUP BY
	A.PCOM_ID

UNION ALL

SELECT
	COUNT(1) DATA_RECEIVE_COUNT,
	'SCMR_PI_COM_ITEM_DAY' TABLE_NAME,
	A.PCOM_ID
FROM
	SCMR_PI_COM_ITEM_DAY A,
	SCMR_RECEIVE_LOG B
WHERE
	A.DATE1 BETWEEN B.DATA_DATE_START AND B.DATA_DATE_END
	AND A.PCOM_ID=B.PCOM_ID
	AND B.TABLE_NAME='SCMR_PI_COM_ITEM_DAY'
	AND B.RECEIVE_DATE='${value}'
GROUP BY
	A.PCOM_ID

UNION ALL

SELECT
	COUNT(1) DATA_RECEIVE_COUNT,
	'SCMR_PI_INVTY_DAY' TABLE_NAME,
	A.PCOM_ID
FROM
	SCMR_PI_INVTY_DAY A,
	SCMR_RECEIVE_LOG B
WHERE
	A.DATE1 BETWEEN B.DATA_DATE_START AND B.DATA_DATE_END
	AND A.PCOM_ID=B.PCOM_ID
	AND B.TABLE_NAME='SCMR_PI_INVTY_DAY'
	AND B.RECEIVE_DATE='${value}'
GROUP BY
	A.PCOM_ID

UNION ALL

SELECT
	COUNT(1) DATA_RECEIVE_COUNT,
	'SCMR_SGP_ORG_ITEM_SW' TABLE_NAME,
	A.PCOM_ID
FROM
	SCMR_SGP_ORG_ITEM_SW A,
	SCMR_RECEIVE_LOG B
WHERE
	A.DATE1 BETWEEN B.DATA_DATE_START AND B.DATA_DATE_END
	AND A.PCOM_ID=B.PCOM_ID
	AND B.TABLE_NAME='SCMR_SGP_ORG_ITEM_SW'
	AND B.RECEIVE_DATE='${value}'
GROUP BY
	A.PCOM_ID

UNION ALL

SELECT
	COUNT(1) DATA_RECEIVE_COUNT,
	'SCMR_SCM_ITEM_FORE' TABLE_NAME,
	A.PCOM_ID
FROM
	SCMR_SCM_ITEM_FORE A,
	SCMR_RECEIVE_LOG B
WHERE
	A.DATE1 BETWEEN B.DATA_DATE_START AND B.DATA_DATE_END
	AND A.PCOM_ID=B.PCOM_ID
	AND B.TABLE_NAME='SCMR_SCM_ITEM_FORE'
	AND B.RECEIVE_DATE='${value}'
GROUP BY
	A.PCOM_ID

UNION ALL

SELECT
	COUNT(1) DATA_RECEIVE_COUNT,
	'SCMR_SGP_COM_ITEM_SW' TABLE_NAME,
	A.PCOM_ID
FROM
	SCMR_SGP_COM_ITEM_SW A,
	SCMR_RECEIVE_LOG B
WHERE
	A.DATE1 BETWEEN B.DATA_DATE_START AND B.DATA_DATE_END
	AND A.PCOM_ID=B.PCOM_ID
	AND B.TABLE_NAME='SCMR_SGP_COM_ITEM_SW'
	AND B.RECEIVE_DATE='${value}'
GROUP BY
	A.PCOM_ID

UNION ALL

SELECT
	COUNT(1) DATA_RECEIVE_COUNT,
	'SCMR_SGP_ITEM_SPW_EXT' TABLE_NAME,
	A.PCOM_ID
FROM
	SCMR_SGP_ITEM_SPW_EXT A,
	SCMR_RECEIVE_LOG B
WHERE
	A.WEEK BETWEEN B.DATA_DATE_START AND B.DATA_DATE_END
	AND A.PCOM_ID=B.PCOM_ID
	AND B.TABLE_NAME='SCMR_SGP_ITEM_SPW_EXT'
	AND B.RECEIVE_DATE='${value}'
GROUP BY
	A.PCOM_ID

UNION ALL

SELECT
	COUNT(1) DATA_RECEIVE_COUNT,
	'SCMR_PI_ITEM_STOCK_MONTH' TABLE_NAME,
	A.PCOM_ID
FROM
	SCMR_PI_ITEM_STOCK_MONTH A,
	SCMR_RECEIVE_LOG B
WHERE
	A.DATE1 BETWEEN B.DATA_DATE_START AND B.DATA_DATE_END
	AND A.PCOM_ID=B.PCOM_ID
	AND B.TABLE_NAME='SCMR_PI_ITEM_STOCK_MONTH'
	AND B.RECEIVE_DATE='${value}'
GROUP BY
	A.PCOM_ID

UNION ALL

SELECT
	COUNT(1) DATA_RECEIVE_COUNT,
	'SCMR_PI_ITEM_ORD_MONTH' TABLE_NAME,
	A.PCOM_ID
FROM
	SCMR_PI_ITEM_ORD_MONTH A,
	SCMR_RECEIVE_LOG B
WHERE
	A.DATE1 BETWEEN B.DATA_DATE_START AND B.DATA_DATE_END
	AND A.PCOM_ID=B.PCOM_ID
	AND B.TABLE_NAME='SCMR_PI_ITEM_ORD_MONTH'
	AND B.RECEIVE_DATE='${value}'
GROUP BY
	A.PCOM_ID

UNION ALL

SELECT
	COUNT(1) DATA_RECEIVE_COUNT,
	'SCMR_SGP_ITEM_MONTH' TABLE_NAME,
	A.PCOM_ID
FROM
	SCMR_SGP_ITEM_MONTH A,
	SCMR_RECEIVE_LOG B
WHERE
	A.MONTH1 BETWEEN B.DATA_DATE_START AND B.DATA_DATE_END
	AND A.PCOM_ID=B.PCOM_ID
	AND B.TABLE_NAME='SCMR_SGP_ITEM_MONTH'
	AND B.RECEIVE_DATE='${value}'
GROUP BY
	A.PCOM_ID

UNION ALL

SELECT
	COUNT(1) DATA_RECEIVE_COUNT,
	'SCMR_SCM_MIC_ITEM_MARKET_STAT' TABLE_NAME,
	A.PCOM_ID
FROM
	SCMR_SCM_MIC_ITEM_MARKET_STAT A,
	SCMR_RECEIVE_LOG B
WHERE
	A.PRI_WEEK BETWEEN B.DATA_DATE_START AND B.DATA_DATE_END
	AND A.PCOM_ID=B.PCOM_ID
	AND B.TABLE_NAME='SCMR_SCM_MIC_ITEM_MARKET_STAT'
	AND B.RECEIVE_DATE='${value}'
GROUP BY
	A.PCOM_ID

UNION ALL

SELECT
	COUNT(1) DATA_RECEIVE_COUNT,
	'SCMR_PI_CUSTTYPE_MONTH' TABLE_NAME,
	A.PCOM_ID
FROM
	SCMR_PI_CUSTTYPE_MONTH A,
	SCMR_RECEIVE_LOG B
WHERE
	A.DATE1 BETWEEN B.DATA_DATE_START AND B.DATA_DATE_END
	AND A.PCOM_ID=B.PCOM_ID
	AND B.TABLE_NAME='SCMR_PI_CUSTTYPE_MONTH'
	AND B.RECEIVE_DATE='${value}'
GROUP BY
	A.PCOM_ID

UNION ALL
