// Generated by CoffeeScript 1.10.0
(function() {
  var eat, foo, food, foods, key, ref, ref1, rlt, value,
    hasProp = {}.hasOwnProperty;

  foo = function() {
    var i, results;
    results = [];
    for (i = 1; i <= 10; i += 2) {
      results.push(console.log('网易'));
    }
    return results;
  };

  foo.apply(null, [1, 2, 3]);

  eat = function(food) {
    console.log('eatting ' + food);
    return food;
  };

  foods = ['broccoli', 'spinach', 'chocolate'];

  rlt = (function() {
    var i, len, results;
    results = [];
    for (i = 0, len = foods.length; i < len; i++) {
      food = foods[i];
      if (food !== 'chocolate') {
        results.push(eat(food));
      }
    }
    return results;
  })();

  rlt = (function() {
    var i, len, results;
    results = [];
    for (i = 0, len = foods.length; i < len; i++) {
      food = foods[i];
      results.push(eat(food));
    }
    return results;
  })();

  ref = [
    {
      x: 1,
      y: 2
    }
  ];
  for (key in ref) {
    value = ref[key];
    eat(key, value);
  }

  ref1 = [
    {
      x: 1,
      y: 2
    }
  ];
  for (key in ref1) {
    if (!hasProp.call(ref1, key)) continue;
    value = ref1[key];
    eat(key, value);
  }

  console.log(['a', 'b', 'c'].slice(0, 2));

  console.log(['a', 'b', 'c'].slice(0, 1));

}).call(this);
