--为每一个工业公司维护流水号
INSERT INTO PUB_IDTABLE 
(ID_ID, ID_VALUE, ID_NAME, ID_PREFIX, IS_PREFIX, ID_LENGTH, IS_SUFFIX, ID_SUFFIX, IS_GLOBAL, ORGAN_ID, ID_TYPE, ID_DATE) 
VALUES('ICA_DIST_PERDIEM_PLAN_ID', 0, '按天编码', 'YYYYMMDD', '1', 4, '0', NULL, '0', #{ICOM_ID}, '03', '20160704');

--为每一个工业公司维护流水号
INSERT INTO PUB_IDTABLE 
(ID_ID, ID_VALUE, ID_NAME, ID_PREFIX, IS_PREFIX, ID_LENGTH, IS_SUFFIX, ID_SUFFIX, IS_GLOBAL, ORGAN_ID, ID_TYPE, ID_DATE) 
VALUES('ICA_DIST_PLAN_ID', 0, '定时配货编码', 'YYYYMMDD', '1', 4, '0', NULL, '0', #{ICOM_ID}, '03', '20160704');

--为每一个工业公司维护流水号
INSERT INTO PUB_IDTABLE 
(ID_ID, ID_VALUE, ID_NAME, ID_PREFIX, IS_PREFIX, ID_LENGTH, IS_SUFFIX, ID_SUFFIX, IS_GLOBAL, ORGAN_ID, ID_TYPE, ID_DATE) 
VALUES('ICA_DIST_REALTIME_PLAN_ID', 0, '实时配货编码', 'YYYYMMDD', '1', 4, '0', NULL, '0', #{ICOM_ID}, '03', '20160704');

--为每一个工业公司维护流水号
INSERT INTO PUB_IDTABLE 
(ID_ID, ID_VALUE, ID_NAME, ID_PREFIX, IS_PREFIX, ID_LENGTH, IS_SUFFIX, ID_SUFFIX, IS_GLOBAL, ORGAN_ID, ID_TYPE, ID_DATE) 
VALUES('ICA_DIST_WARNING_PLAN_ID', 0, '应急配货编码', 'YYYYMMDD', '1', 4, '0', NULL, '0', #{ICOM_ID}, '03', '20160704');

--为每一个工业公司维护流水号
INSERT INTO PUB_IDTABLE 
(ID_ID, ID_VALUE, ID_NAME, ID_PREFIX, IS_PREFIX, ID_LENGTH, IS_SUFFIX, ID_SUFFIX, IS_GLOBAL, ORGAN_ID, ID_TYPE, ID_DATE) 
VALUES('ICA_CO_ID', 0, '订单编码', 'YYYYMMDD', '1', 4, '0', NULL, '0', #{ICOM_ID}, '03', '20160704');

--为每一个工业公司维护流水号
INSERT INTO PUB_IDTABLE 
(ID_ID, ID_VALUE, ID_NAME, ID_PREFIX, IS_PREFIX, ID_LENGTH, IS_SUFFIX, ID_SUFFIX, IS_GLOBAL, ORGAN_ID, ID_TYPE, ID_DATE) 
VALUES('ICA_COTRACT_CONTR_ID', 0, '合同编码', 'YYYYMMDD', '1', 4, '0', NULL, '0', #{ICOM_ID}, '03', '20160704');

INSERT INTO BASE_DICT 
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC) 
VALUES('ICA_OPINION_TYPE', '01', '投放不均衡', '意见类型');

INSERT INTO BASE_DICT 
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC) 
VALUES('ICA_OPINION_TYPE', '02', '满足率过低', '意见类型');