INSERT INTO PUB_COMMON_HELP
(HELP_ID, HELP_TABLE, HELP_TITLE, ROOT_NAME, LEVEL_FIELD, CODE_FIELD, IS_EQUAL_LEN, DETAIL_FIELD, FILIATION_FIELD, CODE_STRU, ID_FIELD, SHORT_FIELD, NAME_FIELD, SHOW_FIELD, RETURN_FIELD, HELP_WHERE, IS_DETAILSEL, IS_MULTSEL, IS_INDVL, SHOW_NAME, HELP_NOTE, HELP_STYLE, DATASOURCE, HELP_INTERCEPTOR)
VALUES('IMR_CUST_FILTER_HELP', 'IMR_CUST_FILTER', '选择分类', NULL, NULL, 'FILTER_ID', NULL, NULL, NULL, NULL, 'FILTER_ID', NULL, 'FILTER_NAME', 'FILTER_NAME', 'FILTER_ID,FILTER_NAME', ' 1=1 AND @WHERE@', '0', '1', '0', 'FILTER_NAME#分类名称#150', NULL, NULL, NULL, NULL);


INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('IMR_CUST_FILTER_INDEX_RULE', '01', '等于', '连续值区间');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('IMR_CUST_FILTER_INDEX_RULE', '02', '不等于', '连续值区间');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('IMR_CUST_FILTER_INDEX_RULE', '03', '大于', '连续值区间');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('IMR_CUST_FILTER_INDEX_RULE', '04', '大于等于', '连续值区间');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('IMR_CUST_FILTER_INDEX_RULE', '05', '小于', '连续值区间');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('IMR_CUST_FILTER_INDEX_RULE', '06', '小于等于', '连续值区间');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('IMR_CUST_FILTER_INDEX_RULE', '07', '介于（含高低值）', '连续值区间');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('IMR_CUST_FILTER_INDEX_RULE', '08', '介于（不含高低值）', '连续值区间');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('IMR_CUST_FILTER_INDEX_RULE', '09', '介于（含高值不含低值）', '连续值区间');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('IMR_CUST_FILTER_INDEX_RULE', '10', '介于（含低值不含高值）', '连续值区间');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('IMR_CUST_FILTER_LEVEL', '01', '本工业', '作用范围');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('IMR_CUST_FILTER_LEVEL', '02', '本部门', '作用范围');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('IMR_CUST_FILTER_LEVEL', '03', '本用户', '作用范围');