CREATE TABLE  IMR_CUST_FILTER(
	ICOM_ID VARCHAR(30) NOT NULL,
	FILTER_ID VARCHAR(30) NOT NULL,
	FILTER_NAME VARCHAR(50) NOT NULL,
	FILTER_LEVEL VARCHAR(2)  DEFAULT '00', --00:全局 01:本工业 02:本销区 03:本用户
	FILTER_ORGAN_ID VARCHAR(30), --'ROOT'：全局 '01'：ICOM_ID '02':销区ORGAN_ID '03':ORGAN_ID
	CRT_USER_ID VARCHAR(30),
	CRT_USER_NAME VARCHAR(30),
	CRT_DATE VARCHAR(8),
	IS_FIXED  VARCHAR(1)  DEFAULT '0', --'0'：未固化分类 '1'：固化分类
	NOTE VARCHAR(200)
	) IN "TD_SALE" INDEX IN "TD_OTHER_IDX" ;
	ALTER TABLE "IMR_CUST_FILTER" 
		ADD CONSTRAINT "IMR_CUST_FILTER_PK" PRIMARY KEY
			("ICOM_ID",
			"FILTER_ID");

--终端价值分类指标表
CREATE TABLE IMR_CUST_FILTER_KIND_INDEX(
	FILTER_ID VARCHAR(30) NOT NULL,
	INDEX_TYPE VARCHAR(2) NOT NULL,--（区域-省、区域-市、区域-县、卷烟-工业 、品牌、规格、时间（年/月、周）、价类、两个集中度？、）
	INDEX_VALUE  VARCHAR(100) NOT NULL,
	INDEX_ATTRIBUTE  VARCHAR(1)  NOT NULL, --1：连续 2：离散
	INDEX_RULE  VARCHAR(2) --1：前开后开 2：前闭后开 3：前开后闭 4：前闭后闭 5：大于 6：大于等于 7：小于 8：小于等于 当离散连续类型为连续时有意义
   ) IN "TD_SALE" INDEX IN "TD_OTHER_IDX" ;
	ALTER TABLE "IMR_CUST_FILTER_KIND_INDEX" 
		ADD CONSTRAINT "IMR_CUST_FILTER_KIND_INDEX_PK" PRIMARY KEY
			("FILTER_ID",
			"INDEX_VALUE",
			"INDEX_TYPE");

--终端价值分类过滤得到的零售户结果集；增加一个时间类型，
CREATE TABLE  IMR_CUST_FILTER_RESULT (
	ICOM_ID VARCHAR(30) NOT NULL,
	FILTER_ID VARCHAR(30) NOT NULL,
	DATE1 VARCHAR(8) NOT NULL,
	CUST_ID VARCHAR(30) NOT NULL,
	CUST_NAME VARCHAR(30) NOT NULL,
	DEPT_ID VARCHAR(30)  NOT  NULL,    --营销部
	CCOM_ID VARCHAR(30) NOT NULL,
	PCOM_ID VARCHAR(30) NOT NULL
) IN "TD_SALE" INDEX IN "TD_OTHER_IDX" ;
ALTER TABLE "IMR_CUST_FILTER_RESULT" 
	ADD CONSTRAINT "IMR_CUST_FILTER_RESULT_PK" PRIMARY KEY
		(
		"ICOM_ID",
		"FILTER_ID",
		 "CUST_ID");

CREATE TABLE IMR_CUST_INDEX_MONTH(
	ICOM_ID VARCHAR(30) NOT NULL,
	CUST_ID VARCHAR(30) NOT NULL,
	MONTH VARCHAR(6) NOT NULL,
	COUNT_ORD DECIMAL(18,2),
	ONCE_QTY DECIMAL(18,2),
	PRICE_SEG_FOCUSE VARCHAR(30),
	BRAND_FOCUSE VARCHAR(30),
	NOTE VARCHAR(128)
)IN "TD_SALE" INDEX IN "TD_OTHER_IDX" ;
ALTER TABLE "IMR_CUST_INDEX_MONTH" 
	ADD CONSTRAINT "IMR_CUST_INDEX_MONTH_PK" PRIMARY KEY
		(
		"ICOM_ID",
		"CUST_ID",
		"MONTH");