INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('ICA_CO_STATUS', '01', '已计算', '配货单状态');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('ICA_CO_STATUS', '02', '已制定', '配货单状态');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('ICA_CO_STATUS', '03', '已共享', '配货单状态');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('ICA_CO_STATUS', '04', '商业已驳回', '配货单状态');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('ICA_CO_STATUS', '05', '商业已确认', '配货单状态');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('ICA_CO_STATUS', '06', '已上报', '配货单状态');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('ICA_CO_STATUS', '07', '审核通过', '配货单状态');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('ICA_CO_STATUS', '08', '审核不通过', '配货单状态');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('ICA_CO_STATUS', '09', '已分解', '配货单状态');