DELETE FROM ICA_DIST_LISTCONFI WHERE ICOM_ID='20530001' AND BUSS_FORM='SALE_RATE_INSERT' AND KEY_NAME='CURR_QTY_TRANS_DISPLAY';

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_INSERT', 'CURR_QTY_TRANS_DISPLAY#CURR_QTY_NOT_DECOMP#CURR_QTY_NOT_SIGN#CURR_QTY_CONTRACT#CURR_QTY_TODAY_CON', '在途量', 190.00000, '1', '1', '0', '1');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_INSERT', 'CURR_QTY_TRANS_DISPLAY', '合计', 190.100000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_INSERT', 'CURR_QTY_NOT_DECOMP', '未分解配货单', 190.200000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_INSERT', 'CURR_QTY_NOT_SIGN', '未签章合同', 190.300000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_INSERT', 'CURR_QTY_CONTRACT', '已鉴章未入库合同', 190.400000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_INSERT', 'CURR_QTY_TODAY_CON', '今日入库合同', 190.500000, '0', '1', '0', '0');


DELETE FROM ICA_DIST_LISTCONFI WHERE ICOM_ID='20530001' AND BUSS_FORM='SALE_RATE_DETAIL' AND KEY_NAME='CURR_QTY_TRANS_DISPLAY';

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_DETAIL', 'CURR_QTY_TRANS_DISPLAY#CURR_QTY_NOT_DECOMP#CURR_QTY_NOT_SIGN#CURR_QTY_CONTRACT#CURR_QTY_TODAY_CON', '在途量', 190.00000, '1', '1', '0', '1');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_DETAIL', 'CURR_QTY_TRANS_DISPLAY', '合计', 190.100000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_DETAIL', 'CURR_QTY_NOT_DECOMP', '未分解配货单', 190.200000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_DETAIL', 'CURR_QTY_NOT_SIGN', '未签章合同', 190.300000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_DETAIL', 'CURR_QTY_CONTRACT', '已鉴章未入库合同', 190.400000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_DETAIL', 'CURR_QTY_TODAY_CON', '今日入库合同', 190.500000, '0', '1', '0', '0');



DELETE FROM ICA_DIST_LISTCONFI WHERE ICOM_ID='20530001' AND BUSS_FORM='COM_EMERGE_VERIFY_UPDATE' AND KEY_NAME='CURR_QTY_TRANS_DISPLAY';

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'COM_EMERGE_VERIFY_UPDATE', 'CURR_QTY_TRANS_DISPLAY#CURR_QTY_NOT_DECOMP#CURR_QTY_NOT_SIGN#CURR_QTY_CONTRACT#CURR_QTY_TODAY_CON', '在途量', 190.00000, '1', '1', '0', '1');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'COM_EMERGE_VERIFY_UPDATE', 'CURR_QTY_TRANS_DISPLAY', '合计', 190.100000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'COM_EMERGE_VERIFY_UPDATE', 'CURR_QTY_NOT_DECOMP', '未分解配货单', 190.200000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'COM_EMERGE_VERIFY_UPDATE', 'CURR_QTY_NOT_SIGN', '未签章合同', 190.300000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'COM_EMERGE_VERIFY_UPDATE', 'CURR_QTY_CONTRACT', '已鉴章未入库合同', 190.400000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'COM_EMERGE_VERIFY_UPDATE', 'CURR_QTY_TODAY_CON', '今日入库合同', 190.500000, '0', '1', '0', '0');

DELETE FROM ICA_DIST_LISTCONFI WHERE ICOM_ID='20530001' AND BUSS_FORM='IND_EMERGE_DETAIL' AND KEY_NAME='CURR_QTY_TRANS_DISPLAY';

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_DETAIL', 'CURR_QTY_TRANS_DISPLAY#CURR_QTY_NOT_DECOMP#CURR_QTY_NOT_SIGN#CURR_QTY_CONTRACT#CURR_QTY_TODAY_CON', '在途量', 190.00000, '1', '1', '0', '1');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_DETAIL', 'CURR_QTY_TRANS_DISPLAY', '合计', 190.100000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_DETAIL', 'CURR_QTY_NOT_DECOMP', '未分解配货单', 190.200000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_DETAIL', 'CURR_QTY_NOT_SIGN', '未签章合同', 190.300000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_DETAIL', 'CURR_QTY_CONTRACT', '已鉴章未入库合同', 190.400000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_DETAIL', 'CURR_QTY_TODAY_CON', '今日入库合同', 190.500000, '0', '1', '0', '0');

DELETE FROM ICA_DIST_LISTCONFI WHERE ICOM_ID='20530001' AND BUSS_FORM='IND_EMERGE_INSERT' AND KEY_NAME='CURR_QTY_TRANS_DISPLAY';

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_INSERT', 'CURR_QTY_TRANS_DISPLAY#CURR_QTY_NOT_DECOMP#CURR_QTY_NOT_SIGN#CURR_QTY_CONTRACT#CURR_QTY_TODAY_CON', '在途量', 190.00000, '1', '1', '0', '1');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_INSERT', 'CURR_QTY_TRANS_DISPLAY', '合计', 190.100000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_INSERT', 'CURR_QTY_NOT_DECOMP', '未分解配货单', 190.200000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_INSERT', 'CURR_QTY_NOT_SIGN', '未签章合同', 190.300000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_INSERT', 'CURR_QTY_CONTRACT', '已鉴章未入库合同', 190.400000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_INSERT', 'CURR_QTY_TODAY_CON', '今日入库合同', 190.500000, '0', '1', '0', '0');

DELETE FROM ICA_DIST_LISTCONFI WHERE ICOM_ID='20530001' AND BUSS_FORM='IND_EMERGE_SUBVERIFY_DETAIL' AND KEY_NAME='CURR_QTY_TRANS_DISPLAY';

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_SUBVERIFY_DETAIL', 'CURR_QTY_TRANS_DISPLAY#CURR_QTY_NOT_DECOMP#CURR_QTY_NOT_SIGN#CURR_QTY_CONTRACT#CURR_QTY_TODAY_CON', '在途量', 190.00000, '1', '1', '0', '1');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_SUBVERIFY_DETAIL', 'CURR_QTY_TRANS_DISPLAY', '合计', 190.100000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_SUBVERIFY_DETAIL', 'CURR_QTY_NOT_DECOMP', '未分解配货单', 190.200000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_SUBVERIFY_DETAIL', 'CURR_QTY_NOT_SIGN', '未签章合同', 190.300000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_SUBVERIFY_DETAIL', 'CURR_QTY_CONTRACT', '已鉴章未入库合同', 190.400000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_SUBVERIFY_DETAIL', 'CURR_QTY_TODAY_CON', '今日入库合同', 190.500000, '0', '1', '0', '0');

DELETE FROM ICA_DIST_LISTCONFI WHERE ICOM_ID='20530001' AND BUSS_FORM='IND_EMERGE_SUBVERIFY_UPDATE' AND KEY_NAME='CURR_QTY_TRANS_DISPLAY';

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_SUBVERIFY_UPDATE', 'CURR_QTY_TRANS_DISPLAY#CURR_QTY_NOT_DECOMP#CURR_QTY_NOT_SIGN#CURR_QTY_CONTRACT#CURR_QTY_TODAY_CON', '在途量', 190.00000, '1', '1', '0', '1');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_SUBVERIFY_UPDATE', 'CURR_QTY_TRANS_DISPLAY', '合计', 190.100000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_SUBVERIFY_UPDATE', 'CURR_QTY_NOT_DECOMP', '未分解配货单', 190.200000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_SUBVERIFY_UPDATE', 'CURR_QTY_NOT_SIGN', '未签章合同', 190.300000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_SUBVERIFY_UPDATE', 'CURR_QTY_CONTRACT', '已鉴章未入库合同', 190.400000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_SUBVERIFY_UPDATE', 'CURR_QTY_TODAY_CON', '今日入库合同', 190.500000, '0', '1', '0', '0');

DELETE FROM ICA_DIST_LISTCONFI WHERE ICOM_ID='20530001' AND BUSS_FORM='IND_EMERGE_UPDATE' AND KEY_NAME='CURR_QTY_TRANS_DISPLAY';

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_UPDATE', 'CURR_QTY_TRANS_DISPLAY#CURR_QTY_NOT_DECOMP#CURR_QTY_NOT_SIGN#CURR_QTY_CONTRACT#CURR_QTY_TODAY_CON', '在途量', 190.00000, '1', '1', '0', '1');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_UPDATE', 'CURR_QTY_TRANS_DISPLAY', '合计', 190.100000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_UPDATE', 'CURR_QTY_NOT_DECOMP', '未分解配货单', 190.200000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_UPDATE', 'CURR_QTY_NOT_SIGN', '未签章合同', 190.300000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_UPDATE', 'CURR_QTY_CONTRACT', '已鉴章未入库合同', 190.400000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_UPDATE', 'CURR_QTY_TODAY_CON', '今日入库合同', 190.500000, '0', '1', '0', '0');

DELETE FROM ICA_DIST_LISTCONFI WHERE ICOM_ID='20530001' AND BUSS_FORM='IND_EMERGE_VERIFY_UPDATE' AND KEY_NAME='CURR_QTY_TRANS_DISPLAY';

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_VERIFY_UPDATE', 'CURR_QTY_TRANS_DISPLAY#CURR_QTY_NOT_DECOMP#CURR_QTY_NOT_SIGN#CURR_QTY_CONTRACT#CURR_QTY_TODAY_CON', '在途量', 190.00000, '1', '1', '0', '1');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_VERIFY_UPDATE', 'CURR_QTY_TRANS_DISPLAY', '合计', 190.100000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_VERIFY_UPDATE', 'CURR_QTY_NOT_DECOMP', '未分解配货单', 190.200000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_VERIFY_UPDATE', 'CURR_QTY_NOT_SIGN', '未签章合同', 190.300000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_VERIFY_UPDATE', 'CURR_QTY_CONTRACT', '已鉴章未入库合同', 190.400000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'IND_EMERGE_VERIFY_UPDATE', 'CURR_QTY_TODAY_CON', '今日入库合同', 190.500000, '0', '1', '0', '0');

DELETE FROM ICA_DIST_LISTCONFI WHERE ICOM_ID='20530001' AND BUSS_FORM='MODIFY_DETAIL' AND KEY_NAME='CURR_QTY_TRANS_DISPLAY';

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'MODIFY_DETAIL', 'CURR_QTY_TRANS_DISPLAY#CURR_QTY_NOT_DECOMP#CURR_QTY_NOT_SIGN#CURR_QTY_CONTRACT#CURR_QTY_TODAY_CON', '在途量', 190.00000, '1', '1', '0', '1');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'MODIFY_DETAIL', 'CURR_QTY_TRANS_DISPLAY', '合计', 190.100000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'MODIFY_DETAIL', 'CURR_QTY_NOT_DECOMP', '未分解配货单', 190.200000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'MODIFY_DETAIL', 'CURR_QTY_NOT_SIGN', '未签章合同', 190.300000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'MODIFY_DETAIL', 'CURR_QTY_CONTRACT', '已鉴章未入库合同', 190.400000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'MODIFY_DETAIL', 'CURR_QTY_TODAY_CON', '今日入库合同', 190.500000, '0', '1', '0', '0');

DELETE FROM ICA_DIST_LISTCONFI WHERE ICOM_ID='20530001' AND BUSS_FORM='MODIFY_UPDATE' AND KEY_NAME='CURR_QTY_TRANS_DISPLAY';

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'MODIFY_UPDATE', 'CURR_QTY_TRANS_DISPLAY#CURR_QTY_NOT_DECOMP#CURR_QTY_NOT_SIGN#CURR_QTY_CONTRACT#CURR_QTY_TODAY_CON', '在途量', 190.00000, '1', '1', '0', '1');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'MODIFY_UPDATE', 'CURR_QTY_TRANS_DISPLAY', '合计', 190.100000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'MODIFY_UPDATE', 'CURR_QTY_NOT_DECOMP', '未分解配货单', 190.200000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'MODIFY_UPDATE', 'CURR_QTY_NOT_SIGN', '未签章合同', 190.300000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'MODIFY_UPDATE', 'CURR_QTY_CONTRACT', '已鉴章未入库合同', 190.400000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'MODIFY_UPDATE', 'CURR_QTY_TODAY_CON', '今日入库合同', 190.500000, '0', '1', '0', '0');

DELETE FROM ICA_DIST_LISTCONFI WHERE ICOM_ID='20530001' AND BUSS_FORM='SALE_RATE_SUBVERIFY_UPDATE' AND KEY_NAME='CURR_QTY_TRANS_DISPLAY';

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_SUBVERIFY_UPDATE', 'CURR_QTY_TRANS_DISPLAY#CURR_QTY_NOT_DECOMP#CURR_QTY_NOT_SIGN#CURR_QTY_CONTRACT#CURR_QTY_TODAY_CON', '在途量', 190.00000, '1', '1', '0', '1');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_SUBVERIFY_UPDATE', 'CURR_QTY_TRANS_DISPLAY', '合计', 190.100000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_SUBVERIFY_UPDATE', 'CURR_QTY_NOT_DECOMP', '未分解配货单', 190.200000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_SUBVERIFY_UPDATE', 'CURR_QTY_NOT_SIGN', '未签章合同', 190.300000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_SUBVERIFY_UPDATE', 'CURR_QTY_CONTRACT', '已鉴章未入库合同', 190.400000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_SUBVERIFY_UPDATE', 'CURR_QTY_TODAY_CON', '今日入库合同', 190.500000, '0', '1', '0', '0');

DELETE FROM ICA_DIST_LISTCONFI WHERE ICOM_ID='20530001' AND BUSS_FORM='SALE_RATE_VERIFY_UPDATE' AND KEY_NAME='CURR_QTY_TRANS_DISPLAY';

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_VERIFY_UPDATE', 'CURR_QTY_TRANS_DISPLAY#CURR_QTY_NOT_DECOMP#CURR_QTY_NOT_SIGN#CURR_QTY_CONTRACT#CURR_QTY_TODAY_CON', '在途量', 190.00000, '1', '1', '0', '1');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_VERIFY_UPDATE', 'CURR_QTY_TRANS_DISPLAY', '合计', 190.100000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_VERIFY_UPDATE', 'CURR_QTY_NOT_DECOMP', '未分解配货单', 190.200000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_VERIFY_UPDATE', 'CURR_QTY_NOT_SIGN', '未签章合同', 190.300000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_VERIFY_UPDATE', 'CURR_QTY_CONTRACT', '已鉴章未入库合同', 190.400000, '0', '1', '0', '0');

INSERT INTO ICA_DIST_LISTCONFI
(ICOM_ID, BUSS_FORM, KEY_NAME, FIELD_NAME, SEQ, SHOW_LEVEL, IS_SHOW, IS_FIXED, IS_USER_CONFI)
VALUES('20530001', 'SALE_RATE_VERIFY_UPDATE', 'CURR_QTY_TODAY_CON', '今日入库合同', 190.500000, '0', '1', '0', '0');
