INSERT INTO PUB_COMMON_HELP
(HELP_ID, HELP_TABLE, HELP_TITLE, ROOT_NAME, LEVEL_FIELD, CODE_FIELD, IS_EQUAL_LEN, DETAIL_FIELD, FILIATION_FIELD, CODE_STRU, ID_FIELD, SHORT_FIELD, NAME_FIELD, SHOW_FIELD, RETURN_FIELD, HELP_WHERE, IS_DETAILSEL, IS_MULTSEL, IS_INDVL, SHOW_NAME, HELP_NOTE, HELP_STYLE, DATASOURCE, HELP_INTERCEPTOR)
VALUES('CRM_MATERIEL_COMMON_HELP', 'CRM_MATERIEL', '物资选择帮助框', '', '', 'MATERIEL_ID', '', '', '', '', 'MATERIEL_ID', '', 'MATERIEL_NAME', 'MATERIEL_ID,MATERIEL_NAME', 'MATERIEL_ID,MATERIEL_NAME,UM_NAME', '1=1 AND @where@', '0', '0', '0', 'MATERIEL_ID#物资编码#80,MATERIEL_NAME#物资名称#200', '', '', '', '');

INSERT INTO PUB_IDTABLE
(ID_ID, ID_VALUE, ID_NAME, ID_PREFIX, IS_PREFIX, ID_LENGTH, IS_SUFFIX, ID_SUFFIX, IS_GLOBAL, ORGAN_ID, ID_TYPE, ID_DATE)
VALUES('CRM_MATERIEL_STORAGE_NUM', 1, '物资出入库单流水号', 'WZ', '1', 20, '0', '', '1', '', '  ', NULL);

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('CRM_MATERIEL_STORAGE_TYPE', '01', '入库', '出入库类型');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('CRM_MATERIEL_STORAGE_TYPE', '02', '分配出库', '出入库类型');


INSERT INTO PUB_FUNCTIONS
(FUNCTION_CODE, FUNCTION_NAME, MODULE_CODE, SEQ, ORGAN_TYPE, IS_MENU, URL, ICON, F_TYPE, TARGET, CP_MENU_ID, DESCRIPTION, STRU_TYPE)
VALUES('crm_materiel_slsman', '终端物资管理（客户经理）', 'crm_personal_05sc', 9, '63', '1', '/custclassification/slsmanMaterielManagerQuery.cmd', '', '0', NULL, 1001, NULL, '02');
INSERT INTO PUB_FUNCTIONS
(FUNCTION_CODE, FUNCTION_NAME, MODULE_CODE, SEQ, ORGAN_TYPE, IS_MENU, URL, ICON, F_TYPE, TARGET, CP_MENU_ID, DESCRIPTION, STRU_TYPE)
VALUES('crm_materiel_saleorg', '终端物资管理（分公司）', 'crm_personal_05sc', 8, '231', '1', '/custclassification/saleOrgMaterielManagerQuery.cmd', '', '0', NULL, 1001, NULL, '02');
INSERT INTO PUB_FUNCTIONS
(FUNCTION_CODE, FUNCTION_NAME, MODULE_CODE, SEQ, ORGAN_TYPE, IS_MENU, URL, ICON, F_TYPE, TARGET, CP_MENU_ID, DESCRIPTION, STRU_TYPE)
VALUES('crm_materiel_com', '终端物资管理（营销中心）', 'crm_personal_05sc', 7, '1011', '1', '/custclassification/comCommaterielManagerQuery.cmd', '', '0', NULL, 1001, NULL, '02');


INSERT INTO PUB_OPERATIONS
(OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ)
VALUES('crm_materiel_slsmanQ', '查询', 'crm_materiel_slsman', '00', '1', 0);
INSERT INTO PUB_OPERATIONS
(OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ)
VALUES('crm_materiel_saleOrgQ', '查询', 'crm_materiel_saleorg', '00', '1', 0);
INSERT INTO PUB_OPERATIONS
(OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ)
VALUES('crm_materiel_comQ', '查询', 'crm_materiel_com', '00', '1', 0);



INSERT INTO PUB_URLS
(URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ)
VALUES('8080815832944301588acca74d041d', '查询', '/custclassification/saleOrgMaterielManagerQuery.cmd', 'crm_materiel_saleOrgQ', 'crm_materiel_saleorg', 'http', NULL, 0);
INSERT INTO PUB_URLS
(URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ)
VALUES('8080815832944301588acc57bf041c', '查询', '/custclassification/slsmanMaterielManagerQuery.cmd', 'crm_materiel_slsmanQ', 'crm_materiel_slsman', 'http', NULL, 0);
INSERT INTO PUB_URLS
(URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ)
VALUES('8080815832944301588a8c93b60416', '查询', '/custclassification/comCommaterielManagerQuery.cmd', 'crm_materiel_comQ', 'crm_materiel_com', 'http', NULL, 0);
