INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('CRM_EVAL_MODEL_STATUS', '00', '新建', '评测模型状态');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('CRM_EVAL_MODEL_STATUS', '01', '待审', '评测模型状态');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('CRM_EVAL_MODEL_STATUS', '02', '已审', '评测模型状态');

DELETE FROM BASE_DICT WHERE DICT_ID='CRM_EVAL_INDEX_TYPE';
INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('CRM_EVAL_INDEX_TYPE', '01', '终端选取指标', '终端评测指标类型');

INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('CRM_EVAL_INDEX_TYPE', '02', '终端评测指标', '终端评测指标类型');

--流水号已存在的不再执行
--DELETE FROM PUB_IDTABLE WHERE ID_ID='CRM_EVAL_MODEL_ID';
INSERT INTO PUB_IDTABLE
(ID_ID, ID_VALUE, ID_NAME, ID_PREFIX, IS_PREFIX, ID_LENGTH, IS_SUFFIX, ID_SUFFIX, IS_GLOBAL, ORGAN_ID, ID_TYPE, ID_DATE)
VALUES('CRM_EVAL_MODEL_ID', 1, '评测模型', '', '0', 15, '0', '', '1', '', '  ', NULL);

INSERT INTO PUB_OPERATIONS
(OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ)
VALUES('crm_evalmodelAudit', '审核', 'crm_evalmodel', '00', '0', 0);

INSERT INTO PUB_URLS
(URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ)
VALUES('808081583294430158998804fb048e', '审核', '/custclassification/rimevalmodel.cmd?method=forAudit', 'crm_evalmodelAudit', 'crm_evalmodel', 'http', NULL, 0);

DELETE FROM PUB_URLS WHERE OPERATION_CODE='plm_evalmodelCopy';
DELETE FROM PUB_ROLE_OPERATION WHERE OPERATION_CODE='plm_evalmodelCopy';
DELETE FROM PUB_OPERATIONS WHERE OPERATION_CODE='plm_evalmodelCopy';

INSERT INTO PUB_OPERATIONS
(OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ)
VALUES('plm_evalmodelCopy', '模型复制', 'crm_evalmodel', '00', '0', 9);

INSERT INTO PUB_URLS
(URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ)
VALUES('8080814b5ce469014b713f4b770006', '模型复制', '/custclassification/rimevalmodel.cmd?method=forCopyModel', 'plm_evalmodelCopy', 'crm_evalmodel', 'http', NULL, 0);
