ALTER TABLE "ICA_PLAN_HISOPIN_ITEM"  DROP CONSTRAINT ICA_PLAN_HISOPIN_ITEM_PK;
ALTER TABLE "ICA_PLAN_HISOPIN_ITEM"  ALTER COLUMN CO_ID SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE ICA_PLAN_HISOPIN_ITEM');
ALTER TABLE "ICA_PLAN_HISOPIN_ITEM" 
	ADD CONSTRAINT "ICA_PLAN_HISOPIN_ITEM_PK" PRIMARY KEY
		("OPINION_ID",
		 "ITEM_ID","CO_ID");