ALTER TABLE IMR_ITEM_COMPETE ADD COLUMN COMPETE_TYPE CHAR(1) NOT NULL;
ALTER TABLE "IMR_ITEM_COMPETE" DROP CONSTRAINT "IMR_ITEM_COMPETE_PK";
ALTER TABLE "IMR_ITEM_COMPETE" 
	ADD CONSTRAINT "IMR_ITEM_COMPETE_PK" PRIMARY KEY
		("ICOM_ID",
		 "PACK_BAR",
		 "PCOM_ID",
		 "COM_ID",
		 "COMPETE_PACK_BAR",
		 "COMPETE_TYPE");

CREATE TABLE IMR_PRICE_SEG(
	ICOM_ID VARCHAR(30) NOT NULL,
	PRICE_SEG_ID VARCHAR(30) NOT NULL,
	PRICE_SEG_NAME VARCHAR(30) NOT NULL,
	PRICE_FROM_VAL VARCHAR(30) NOT NULL,
	PRICE_TO_VAL VARCHAR(30) NOT NULL,
	NOTE VARCHAR(128)
) IN "TD_SALE" INDEX IN "TD_OTHER_IDX";
ALTER TABLE "IMR_PRICE_SEG" 
	ADD CONSTRAINT "IMR_PRICE_SEG_PK" PRIMARY KEY
		("ICOM_ID",
		 "PRICE_SEG_ID");
		 
CREATE TABLE IMR_PRICE_SEG_RANK_FIVE(
	ICOM_ID VARCHAR(30) NOT NULL,
	PRICE_SEG_ID VARCHAR(30) NOT NULL,
	CCOM VARCHAR(30) NOT NULL,
	RANK INTEGER NOT NULL,
	PACK_BAR VARCHAR(30) NOT NULL,
	NOTE VARCHAR(128)
) IN "TD_SALE" INDEX IN "TD_OTHER_IDX";
ALTER TABLE "IMR_PRICE_SEG_RANK_FIVE" 
	ADD CONSTRAINT "IMR_PRICE_SEG_RANK_FIVE_PK" PRIMARY KEY
		("ICOM_ID",
		 "PRICE_SEG_ID",
		 "CCOM",
		 "RANK",
		 "PACK_BAR");