CREATE TABLE SCMR_SCM_MIC_ALL_ITEM_WEEK  ( 
	PCOM_ID        	VARCHAR(30) NOT NULL,
	CCOM_ID        	VARCHAR(30) NOT NULL,
	COM_ID         	VARCHAR(30) NOT NULL,
	PRI_WEEK       	VARCHAR(10) NOT NULL,
	ITEM_ID        	VARCHAR(30) NOT NULL,
	PACK_BAR       	VARCHAR(30) NOT NULL,
	WHSE_SALE      	DECIMAL(18,6),
	WHSE_AVG       	DECIMAL(18,6),
	QTY_SOLD       	DECIMAL(18,6),
	SALE_QTY       	DECIMAL(18,6),
	RETAIL_BOX_PRI 	DECIMAL(18,6),
	RETAIL_PARK_PRI	DECIMAL(18,6),
	TRADE_PRI_N    	DECIMAL(18,6),
	BOX_PRI_INDEX  	DECIMAL(18,6),
	PARK_PRI_INDEX 	DECIMAL(18,6),
	TRADE_PRI_INDEX	DECIMAL(18,6),
	SALE_RATE      	DECIMAL(18,6),
	RESALE_RATE    	DECIMAL(18,6),
	SALE_WHSE      	DECIMAL(18,6),
	SALE_WHSE_B    	DECIMAL(18,6),
	OOS_RATE       	DECIMAL(18,6),
	OOS_RATE_COM   	DECIMAL(18,6),
	PRI3           	DECIMAL(18,6),
	PRI4           	DECIMAL(18,6),
	ZERO_DAY_NUM   	DECIMAL(18,6),
	ORDER_FILL_RATE	DECIMAL(18,6),
	SALE_SOLD_RATE 	DECIMAL(18,6),
	BOX_SALE_QTY   	DECIMAL(18,6),
	PARK_SALE_QTY  	DECIMAL(18,6),
	QTY_NEED_C     	DECIMAL(18,6),
	QTY_SOLD_C     	DECIMAL(18,6),
	GROSS_RATE     	DECIMAL(18,6),
	PARK_SALE_B    	DECIMAL(18,6),
	SUMM_TYPE      	CHAR(1) NOT NULL,
	PRI_MONTH      	CHAR(6) NOT NULL,
	CUST_NUM       	INTEGER
) IN "TD_SALE" INDEX IN "TD_OTHER_IDX" ;  


-- DDL Statements for Primary Key on Table "SCMR_SCM_MIC_ALL_ITEM_WEEK"

ALTER TABLE "SCMR_SCM_MIC_ALL_ITEM_WEEK" 
	ADD CONSTRAINT "SCMR_SCM_MIC_ALL_ITEM_WEEK_PK" PRIMARY KEY
		("CCOM_ID",
		 "SUMM_TYPE",
		 "PRI_MONTH",
		 "PRI_WEEK",
		 "ITEM_ID");


------------------------------------------------
-- DDL Statements for Table "SCMR_SGP_ITEM_MONTH"
------------------------------------------------
 

CREATE TABLE SCMR_SGP_ITEM_MONTH
	(
		PCOM_ID VARCHAR(30) NOT NULL,
		CCOM_ID VARCHAR(30) NOT NULL,
		COM_ID VARCHAR(30) NOT NULL,
		PACK_BAR VARCHAR(30) NOT NULL,
		T_SIZE INTEGER NOT NULL DEFAULT 200,
		ITEM_ID VARCHAR(30) NOT NULL,
		MONTH1 CHARACTER(6) NOT NULL,
		YEAR1 CHARACTER(4) NOT NULL,
		BEGIN_DAY CHARACTER(8) NOT NULL,
		END_DAY CHARACTER(8) NOT NULL,
		SUPPLY_WAY VARCHAR(2) NOT NULL,
		TACTIC_TYPE VARCHAR(2) NOT NULL,
		CUST_COUNT_PLAN INTEGER NOT NULL DEFAULT 0,
		QTY_IOM DECIMAL(18,2) DEFAULT 0 NOT NULL,
		QTY_PURCH DECIMAL(18,2) DEFAULT 0 NOT NULL,
		QTY_SUPPLY DECIMAL(18,2) DEFAULT 0 NOT NULL,
		CUST_COUNT_SUPPLY INTEGER NOT NULL DEFAULT 0,
		QTY_NEED DECIMAL(18,2) NOT NULL DEFAULT 0,
		CO_COUNT_NEED INTEGER NOT NULL DEFAULT 0,
		CUST_COUNT_NEED INTEGER NOT NULL DEFAULT 0,
		QTY_ORD DECIMAL(18,2) DEFAULT 0 NOT NULL,
		AMT_ORD DECIMAL(18,2) DEFAULT 0 NOT NULL,
		CO_COUNT_ORD INTEGER NOT NULL DEFAULT 0,
		CUST_COUNT_ORD INTEGER NOT NULL DEFAULT 0,
		CO_COUNT_ORDFULL INTEGER NOT NULL DEFAULT 0,
		DAY_COUNT_MONTH INTEGER NOT NULL DEFAULT 0,
		DAY_COUNT_OUT_STOCK INTEGER NOT NULL DEFAULT 0,
		QTY_ORD_PERCENT_TOP1 DECIMAL(18,2) DEFAULT 0 NOT NULL,
		QTY_ORD_TOP50 DECIMAL(18,2) DEFAULT 0 NOT NULL,
		UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP
	) IN "TD_SALE" INDEX IN "TD_OTHER_IDX" ;  


-- DDL Statements for Primary Key on Table "SCMR_SGP_ITEM_MONTH"

ALTER TABLE "SCMR_SGP_ITEM_MONTH" 
	ADD CONSTRAINT "SCMR_SGP_ITEM_MONTH_PK" PRIMARY KEY
		("CCOM_ID",
		 "ITEM_ID",
		 "MONTH1");

------------------------------------------------
-- DDL Statements for Table "SCMR_PI_ITEM_ORD_MONTH"
------------------------------------------------
 CREATE TABLE SCMR_PI_ITEM_ORD_MONTH
	(
		PCOM_ID VARCHAR(30) NOT NULL,
		CCOM_ID VARCHAR(30) NOT NULL,
		COM_ID VARCHAR(30) NOT NULL,
		PACK_BAR VARCHAR(30) NOT NULL,
		T_SIZE INTEGER NOT NULL DEFAULT 200,
		ITEM_ID VARCHAR(30) NOT NULL,
		DATE1 CHARACTER(6) NOT NULL,
		CUST_COUNT_NORMAL INTEGER NOT NULL DEFAULT 0,
		CUST_COUNT_NEED INTEGER NOT NULL DEFAULT 0,
		CO_COUNT_NEED INTEGER NOT NULL DEFAULT 0,
		QTY_NEED DECIMAL(18,2) NOT NULL DEFAULT 0,
		CUST_COUNT_ORD INTEGER NOT NULL DEFAULT 0,
		CO_COUNT_ORD INTEGER NOT NULL DEFAULT 0,
		QTY_ORD DECIMAL(18,2) NOT NULL DEFAULT 0,
		AMT_ORD DECIMAL(18,2) NOT NULL DEFAULT 0,
		CUST_COUNT_NEED_MANY INTEGER NOT NULL DEFAULT 0,
		QTY_NEED_NEED_MANY DECIMAL(18,2) NOT NULL DEFAULT 0,
		QTY_ORD_NEED_MANY DECIMAL(18,2) NOT NULL DEFAULT 0,
		AMT_ORD_NEED_MANY DECIMAL(18,2) NOT NULL DEFAULT 0,
		CUST_COUNT_ORD_MANY INTEGER NOT NULL DEFAULT 0,
		QTY_NEED_ORD_MANY DECIMAL(18,2) NOT NULL DEFAULT 0,
		QTY_ORD_ORD_MANY DECIMAL(18,2) NOT NULL DEFAULT 0,
		AMT_ORD_ORD_MANY DECIMAL(18,2) NOT NULL DEFAULT 0,
		CUST_COUNT_ORD_EVERY INTEGER NOT NULL DEFAULT 0,
		QTY_NEED_ORD_EVERY DECIMAL(18,2) NOT NULL DEFAULT 0,
		QTY_ORD_ORD_EVERY DECIMAL(18,2) NOT NULL DEFAULT 0,
		AMT_ORD_ORD_EVERY DECIMAL(18,2) NOT NULL DEFAULT 0,
		UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP
	) IN "TD_SALE" INDEX IN "TD_OTHER_IDX" ;  

-- DDL Statements for Primary Key on Table "SCMR_PI_ITEM_ORD_MONTH"

ALTER TABLE "SCMR_PI_ITEM_ORD_MONTH" 
	ADD PRIMARY KEY
		("CCOM_ID",
		 "ITEM_ID",
		 "DATE1");

------------------------------------------------
-- DDL Statements for Table "SCMR_PI_ITEM_STOCK_MONTH"
------------------------------------------------
 

CREATE TABLE "SCMR_PI_ITEM_STOCK_MONTH"  (
		PCOM_ID VARCHAR(30) NOT NULL,
		CCOM_ID VARCHAR(30) NOT NULL,
		COM_ID VARCHAR(30) NOT NULL,
		ITEM_ID VARCHAR(30) NOT NULL,
		PACK_BAR VARCHAR(30) NOT NULL,
		T_SIZE INTEGER NOT NULL DEFAULT 200,
		DATE1 CHARACTER(6) NOT NULL,
		QTY_IOM DECIMAL(18,2) NOT NULL DEFAULT 0,
		QTY_PURCH DECIMAL(18,2) NOT NULL DEFAULT 0,
		QTY_EOM DECIMAL(18,2) NOT NULL DEFAULT 0,
		QTY_NEED DECIMAL(18,2) NOT NULL DEFAULT 0,
		QTY_SOLD DECIMAL(18,2) NOT NULL DEFAULT 0,
		QTY_ALLOCATION DECIMAL(18,2) NOT NULL DEFAULT 0,
		QTY_AVG DECIMAL(18,2) NOT NULL DEFAULT 0,
		DAY_MONTH INTEGER NOT NULL DEFAULT 0,
		DAY_NORMAL INTEGER NOT NULL DEFAULT 0,
		DAY_OUT_STOCK INTEGER NOT NULL DEFAULT 0,
		DAY_OUT_SUPPLY INTEGER NOT NULL DEFAULT 0,
		UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP)   
		 IN "TD_SALE" INDEX IN "TD_OTHER_IDX" ; 


-- DDL Statements for Primary Key on Table "SCMR_PI_ITEM_STOCK_MONTH"

ALTER TABLE "SCMR_PI_ITEM_STOCK_MONTH" 
	ADD CONSTRAINT "SCMRPIITEMSTOCK_PK" PRIMARY KEY
		("CCOM_ID",
		 "ITEM_ID",
		 "DATE1");



------------------------------------------------
-- DDL Statements for Table "SCMR_PI_ITEM_MKT_MONTH"
------------------------------------------------
 

CREATE TABLE "SCMR_PI_ITEM_MKT_MONTH"  (
		PCOM_ID VARCHAR(30) NOT NULL,
		CCOM_ID VARCHAR(30) NOT NULL,
		COM_ID VARCHAR(30) NOT NULL,
		PACK_BAR VARCHAR(30) NOT NULL,
		T_SIZE INTEGER NOT NULL DEFAULT 200,
		ITEM_ID VARCHAR(30) NOT NULL,
		DATE1 CHARACTER(6) NOT NULL,
		DEPT_COUNT_NORMAL INTEGER NOT NULL DEFAULT 0,
		DEPT_COUNT_SALE INTEGER NOT NULL DEFAULT 0,
		CUST_COUNT_NORMAL INTEGER NOT NULL DEFAULT 0,
		CUST_COUNT_YEAR INTEGER NOT NULL DEFAULT 0,
		CUST_COUNT_ORD INTEGER NOT NULL DEFAULT 0,
		CUST_COUNT_INFLOW INTEGER NOT NULL DEFAULT 0,
		QTY_ORD_INFLOW DECIMAL(18, 2) NOT NULL DEFAULT 0,
		CUST_COUNT_OUTFLOW INTEGER NOT NULL DEFAULT 0,
		QTY_ORD_OUTFLOW DECIMAL(18, 2) NOT NULL DEFAULT 0,
		CUST_COUNT_STABLE INTEGER NOT NULL DEFAULT 0,
		QTY_ORD_STABLE DECIMAL(18, 2) NOT NULL DEFAULT 0,
		CUST_COUNT_OOS INTEGER NOT NULL DEFAULT 0,
		QTY_NEED_OOS DECIMAL(18, 2) NOT NULL DEFAULT 0,
		UPDATE_TIME TIMESTAMP DEFAULT CURRENT TIMESTAMP )
		IN "TD_SALE" INDEX IN "TD_OTHER_IDX" ;


-- DDL Statements for Primary Key on Table "SCMR_PI_ITEM_MKT_MONTH"

ALTER TABLE "SCMR_PI_ITEM_MKT_MONTH" 
	ADD CONSTRAINT "SCMR_PI_ITEM_MKT_MONTH_PK" PRIMARY KEY
		("CCOM_ID",
		 "ITEM_ID",
		 "DATE1");