CREATE TABLE SCMR_SGP_ITEM_ORGSEG_WEEK  ( 
	PCOM_ID          	VARCHAR(30) NOT NULL,
	CCOM_ID          	VARCHAR(30) NOT NULL,
	COM_ID           	VARCHAR(30) NOT NULL,
	PACK_BAR         	VARCHAR(30) NOT NULL,
	T_SIZE           	INTEGER DEFAULT 200 NOT NULL,
	ITEM_ID          	VARCHAR(30) NOT NULL,
	WEEK             	CHARACTER(7) NOT NULL,
	ORGAN_ID         	VARCHAR(30) NOT NULL,
	ORGAN_TYPE       	VARCHAR(10) NOT NULL,
	CUST_SEG         	VARCHAR(10) NOT NULL,
	MONTH1           	CHARACTER(6) NOT NULL,
	YEAR1            	CHARACTER(4) NOT NULL,
	BEGIN_DAY        	CHARACTER(8) NOT NULL,
	END_DAY          	CHARACTER(8) NOT NULL,
	CUST_COUNT_PLAN  	INTEGER DEFAULT 0 NOT NULL,
	CUST_COUNT_SUPPLY	INTEGER DEFAULT 0 NOT NULL,
	QTY_SUPPLY       	DECIMAL(18,2) DEFAULT 0 NOT NULL,
	QTY_NEED         	DECIMAL(18,2) DEFAULT 0 NOT NULL,
	CO_COUNT_NEED    	INTEGER DEFAULT 0 NOT NULL,
	CUST_COUNT_NEED  	INTEGER DEFAULT 0 NOT NULL,
	QTY_ORD          	DECIMAL(18,2) DEFAULT 0 NOT NULL,
	AMT_ORD          	DECIMAL(18,2) DEFAULT 0 NOT NULL,
	CO_COUNT_ORD     	INTEGER DEFAULT 0 NOT NULL,
	CUST_COUNT_ORD   	INTEGER DEFAULT 0 NOT NULL,
	CO_COUNT_ORDFULL 	INTEGER DEFAULT 0 NOT NULL,
	UPDATE_TIME      	TIMESTAMP CURRENT_TIMESTAMP TIMESTAMP NOT NULL
)TABLESPACE "TD_SALE";
ALTER TABLE "SCMR_SGP_ITEM_ORGSEG_WEEK" 
	ADD CONSTRAINT "SCMR_SGP_ITEM_ORGSEG_WEEK_PK" PRIMARY KEY(CCOM_ID,ITEM_ID,WEEK,ORGAN_ID,ORGAN_TYPE,CUST_SEG)
		USING INDEX TABLESPACE "TD_OTHER_IDX";

CREATE TABLE ICA_COM_SUPPLY_FEEDBACK(
	FEEDBACK_ID VARCHAR(30) NOT NULL,
	ICOM_ID VARCHAR(30) NOT NULL,
	PCOM_ID VARCHAR(30) NOT NULL,
	CCOM_ID VARCHAR(30) NOT NULL,
	PRI_WEEK VARCHAR(7) NOT NULL,
	ITEM_ID VARCHAR(30) NOT NULL
)TABLESPACE "TD_SALE";
ALTER TABLE "ICA_COM_SUPPLY_FEEDBACK" 
	ADD CONSTRAINT "ICA_COM_SUPPLY_FEEDBACK_PK" PRIMARY KEY(FEEDBACK_ID) USING INDEX TABLESPACE "TD_OTHER_IDX";

CREATE TABLE ICA_COM_SUPPLY_FEEDBACK_DETAIL(
	FEEDBACK_ID VARCHAR(30) NOT NULL,
	FEEDBACK_TYPE CHAR(2) NOT NULL,
	FEEDBACK_CONTENT VARCHAR(200) NOT NULL,
	CRT_DATE VARCHAR(30) NOT NULL,
	CRT_TIME VARCHAR(7) NOT NULL,
	CRT_USER_ID VARCHAR(30) NOT NULL,
	CRT_USER_NAME VARCHAR(30) NOT NULL
)TABLESPACE "TD_SALE";
ALTER TABLE  "ICA_COM_SUPPLY_FEEDBACK_DETAIL" 
	ADD CONSTRAINT ICA_COM_SUPPLY_FB_DETAIL_PK PRIMARY KEY
		(FEEDBACK_ID,FEEDBACK_TYPE) USING INDEX TABLESPACE "TD_OTHER_IDX";