
INSERT INTO PUB_FUNCTIONS
(FUNCTION_CODE, FUNCTION_NAME, MODULE_CODE, SEQ, ORGAN_TYPE, IS_MENU, URL, ICON, F_TYPE, TARGET, CP_MENU_ID, DESCRIPTION, STRU_TYPE)
VALUES('ica_tactic', '商业投放策略', 'ica_collaboration', 1, '6701', '1', '/collaboration/tactic_query_init.cmd', '', '0', NULL, 1001, NULL, '11');

INSERT INTO PUB_OPERATIONS
(OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ)
VALUES('ica_tacticQ', '商业投放策略', 'ica_tactic', '00', '1', 0);


INSERT INTO PUB_URLS
(URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ)
VALUES('ee8150586ff9720158bec460fe0003', '商业投放策略', '/collaboration/tactic_query_init.cmd', 'ica_tacticQ', 'ica_tactic', 'http', NULL, 0);

DELETE FROM BASE_DICT WHERE DICT_ID='IMR_SUPPLY_WAY_ENUM';
INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('IMR_SUPPLY_WAY_ENUM', '21', '按档位投放', '投放方式');
INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('IMR_SUPPLY_WAY_ENUM', '30', '按需投放', '投放方式');
INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('IMR_SUPPLY_WAY_ENUM', '20', '按档位结合价位段投放', '投放方式');
INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('IMR_SUPPLY_WAY_ENUM', '22', '按价位段投放', '投放方式');
INSERT INTO BASE_DICT
(DICT_ID, DICT_KEY, DICT_VALUE, DICT_DESC)
VALUES('IMR_SUPPLY_WAY_ENUM', '10', '选点限量', '投放方式');
