CREATE TABLE SCMR_SGP_ITEM_ORGSEG_WEEK  ( 
	PCOM_ID          	VARCHAR(30) NOT NULL,
	CCOM_ID          	VARCHAR(30) NOT NULL,
	COM_ID           	VARCHAR(30) NOT NULL,
	PACK_BAR         	VARCHAR(30) NOT NULL,
	T_SIZE           	INTEGER NOT NULL DEFAULT 200,
	ITEM_ID          	VARCHAR(30) NOT NULL,
	WEEK             	CHARACTER(7) NOT NULL,
	ORGAN_ID         	VARCHAR(30) NOT NULL,
	ORGAN_TYPE       	VARCHAR(10) NOT NULL,
	CUST_SEG         	VARCHAR(10) NOT NULL,
	MONTH1           	CHARACTER(6) NOT NULL,
	YEAR1            	CHARACTER(4) NOT NULL,
	BEGIN_DAY        	CHARACTER(8) NOT NULL,
	END_DAY          	CHARACTER(8) NOT NULL,
	CUST_COUNT_PLAN  	INTEGER NOT NULL DEFAULT 0,
	CUST_COUNT_SUPPLY	INTEGER NOT NULL DEFAULT 0,
	QTY_SUPPLY       	DECIMAL(18,2) NOT NULL DEFAULT 0,
	QTY_NEED         	DECIMAL(18,2) NOT NULL DEFAULT 0,
	CO_COUNT_NEED    	INTEGER NOT NULL DEFAULT 0,
	CUST_COUNT_NEED  	INTEGER NOT NULL DEFAULT 0,
	QTY_ORD          	DECIMAL(18,2) NOT NULL DEFAULT 0,
	AMT_ORD          	DECIMAL(18,2) NOT NULL DEFAULT 0,
	CO_COUNT_ORD     	INTEGER NOT NULL DEFAULT 0,
	CUST_COUNT_ORD   	INTEGER NOT NULL DEFAULT 0,
	CO_COUNT_ORDFULL 	INTEGER NOT NULL DEFAULT 0,
	UPDATE_TIME      	TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP
)IN TD_SALE INDEX IN TD_OTHER_IDX;
ALTER TABLE "SCMR_SGP_ITEM_ORGSEG_WEEK" 
	ADD CONSTRAINT "SCMR_SGP_ITEM_ORGSEG_WEEK_PK" PRIMARY KEY(CCOM_ID,ITEM_ID,WEEK,ORGAN_ID,ORGAN_TYPE,CUST_SEG);

CREATE TABLE ICA_COM_SUPPLY_FEEDBACK(
	FEEDBACK_ID VARCHAR(30) NOT NULL,
	ICOM_ID VARCHAR(30) NOT NULL,
	PCOM_ID VARCHAR(30) NOT NULL,
	CCOM_ID VARCHAR(30) NOT NULL,
	PRI_WEEK VARCHAR(7) NOT NULL,
	ITEM_ID VARCHAR(30) NOT NULL
)IN TD_SALE INDEX IN TD_OTHER_IDX;
ALTER TABLE "ICA_COM_SUPPLY_FEEDBACK" 
	ADD CONSTRAINT "ICA_COM_SUPPLY_FEEDBACK_PK" PRIMARY KEY(FEEDBACK_ID);


CREATE TABLE ICA_COM_SUPPLY_FEEDBACK_DETAIL(
	FEEDBACK_ID VARCHAR(30) NOT NULL,
	FEEDBACK_TYPE CHAR(2) NOT NULL,
	FEEDBACK_CONTENT VARCHAR(200) NOT NULL,
	CRT_DATE VARCHAR(30) NOT NULL,
	CRT_TIME VARCHAR(7) NOT NULL,
	CRT_USER_ID VARCHAR(30) NOT NULL,
	CRT_USER_NAME VARCHAR(30) NOT NULL
)IN TD_SALE INDEX IN TD_OTHER_IDX;
ALTER TABLE "ICA_COM_SUPPLY_FEEDBACK_DETAIL" 
	ADD CONSTRAINT "ICA_COM_SUPPLY_FEEDBACK_DETAIL_PK" PRIMARY KEY(FEEDBACK_ID,FEEDBACK_TYPE);
