CREATE TABLE "SCMR_SCM_ITEM_FORE" (
	"ICOM_ID" VARCHAR(30) NOT NULL,
	"COM_ID" VARCHAR(30) NOT NULL ,
	"CCOM_ID" VARCHAR(30) NOT NULL ,
	"PCOM_ID" VARCHAR(30) NOT NULL ,
	"SOBJECT_ID" VARCHAR(30) NOT NULL ,
	"OBJECT_ID" VARCHAR(30) NOT NULL ,
	"ORGAN_TYPE" VARCHAR(4) NOT NULL ,
	"DATE1" VARCHAR(8) NOT NULL , 
	"DATE_TYPE" CHAR(3) NOT NULL , 
	"PACK_BAR" VARCHAR(30) NOT NULL ,
	"ITEM_ID" VARCHAR(30) NOT NULL , 
	"MODEL_ID" VARCHAR(4) NOT NULL , 
	"INDEX_ID" VARCHAR(30) NOT NULL , 
	"QTY_FORECAST" DECIMAL(18,2) )
	IN "TD_SALE" INDEX IN "TD_OTHER_IDX" ;
ALTER TABLE "SCMR_SCM_ITEM_FORE"
	ADD CONSTRAINT "SCMR_SCM_ITEM_FORE_PK" PRIMARY KEY
		("ICOM_ID",
		"CCOM_ID",
		"OBJECT_ID",
		"DATE1",
		"ITEM_ID",
		"MODEL_ID",
		"INDEX_ID");