CREATE TABLE  IMR_CUST_FILTER(
	ICOM_ID VARCHAR(30) NOT NULL,
	FILTER_ID VARCHAR(30) NOT NULL,
	FILTER_NAME VARCHAR(50) NOT NULL,
	FILTER_LEVEL VARCHAR(2)  DEFAULT '00', --00:全局 01:本工业 02:本销区 03:本用户
	FILTER_ORGAN_ID VARCHAR(30), --'ROOT'：全局 '01'：ICOM_ID '02':销区ORGAN_ID '03':ORGAN_ID
	CRT_USER_ID VARCHAR(30),
	CRT_USER_NAME VARCHAR(30),
	CRT_DATE VARCHAR(8),
	IS_FIXED  VARCHAR(1)  DEFAULT '0', --'0'：未固化分类 '1'：固化分类
	NOTE VARCHAR(200)
	) IN "TD_SALE" INDEX IN "TD_OTHER_IDX" ;
	ALTER TABLE "IMR_CUST_FILTER" 
		ADD CONSTRAINT "IMR_CUST_FILTER_PK" PRIMARY KEY
			("ICOM_ID",
			"FILTER_ID");

--终端价值分类指标表
CREATE TABLE IMR_CUST_FILTER_KIND_INDEX(
	FILTER_ID VARCHAR(30) NOT NULL,
	INDEX_TYPE VARCHAR(2) NOT NULL,--（区域-省、区域-市、区域-县、卷烟-工业 、品牌、规格、时间（年/月、周）、价类、两个集中度？、）
	INDEX_VALUE  VARCHAR(100) NOT NULL,
	INDEX_ATTRIBUTE  VARCHAR(1)  NOT NULL, --1：连续 2：离散
	INDEX_RULE  VARCHAR(2) --1：前开后开 2：前闭后开 3：前开后闭 4：前闭后闭 5：大于 6：大于等于 7：小于 8：小于等于 当离散连续类型为连续时有意义
   ) IN "TD_SALE" INDEX IN "TD_OTHER_IDX" ;
	ALTER TABLE "IMR_CUST_FILTER_KIND_INDEX" 
		ADD CONSTRAINT "IMR_CUST_FILTER_KIND_INDEX_PK" PRIMARY KEY
			("FILTER_ID",
			"INDEX_VALUE",
			"INDEX_TYPE");

--终端价值分类过滤得到的零售户结果集；增加一个时间类型，
CREATE TABLE  IMR_CUST_FILTER_RESULT (
	ICOM_ID VARCHAR(30) NOT NULL,
	FILTER_ID VARCHAR(30) NOT NULL,
	DATE1 VARCHAR(8) NOT NULL,
	CUST_ID VARCHAR(30) NOT NULL,
	CUST_NAME VARCHAR(30) NOT NULL,
	DEPT_ID VARCHAR(30)  NOT  NULL,    --营销部
	CCOM_ID VARCHAR(30) NOT NULL,
	PCOM_ID VARCHAR(30) NOT NULL
) IN "TD_SALE" INDEX IN "TD_OTHER_IDX" ;
ALTER TABLE "IMR_CUST_FILTER_RESULT" 
	ADD CONSTRAINT " IMR_CUST_FILTER_RESULT_PK" PRIMARY KEY
		(
		"ICOM_ID",
		"FILTER_ID",
		 "CUST_ID");

--新建一个指标基础表	
IMR_INDEX_BASE
工业  指标    是否使用  顺序


INSERT INTO PUB_COMMON_HELP
(HELP_ID, HELP_TABLE, HELP_TITLE, ROOT_NAME, LEVEL_FIELD, CODE_FIELD, IS_EQUAL_LEN, DETAIL_FIELD, FILIATION_FIELD, CODE_STRU, ID_FIELD, SHORT_FIELD, NAME_FIELD, SHOW_FIELD, RETURN_FIELD, HELP_WHERE, IS_DETAILSEL, IS_MULTSEL, IS_INDVL, SHOW_NAME, HELP_NOTE, HELP_STYLE, DATASOURCE, HELP_INTERCEPTOR)
VALUES('IMR_CUST_FILTER_HELP', 'IMR_CUST_FILTER', '选择分类', NULL, NULL, 'FILTER_ID', NULL, NULL, NULL, NULL, 'FILTER_ID', NULL, 'FILTER_NAME', 'FILTER_NAME', 'FILTER_ID,FILTER_NAME', ' 1=1 AND @WHERE@', '0', '1', '0', 'FILTER_NAME#分类名称#150', NULL, NULL, NULL, NULL);

1、终端价值分析 工作计划
	筛选条件集合维护（增删改查） 1天 6h
	固化集合维护（增删改查） 2天 12h
	定时器执行 1天 6h
	趋势分析	1天 6h