ALTER TABLE ICA_WHSE DROP COLUMN FACT_ID;
CALL SYSPROC.ADMIN_CMD('REORG TABLE ICA_WHSE');

CREATE TABLE "ICA_WHSE_ITEM"  (
		  "WHSE_ID" VARCHAR(30) NOT NULL , 
		  "ITEM_ID" VARCHAR(30) NOT NULL , 
		  "IS_DEFAULT" CHAR(1) , 
		  "ICOM_ID" VARCHAR(30) )   
		 IN "TD_SALE" INDEX IN "TD_OTHER_IDX" ;
ALTER TABLE  "ICA_WHSE_ITEM" 
	ADD PRIMARY KEY
		("WHSE_ID",
		 "ITEM_ID");