--DEPT_COUNT_SALE/DEPT_COUNT_NORMAL RATE,--覆盖率（%）
--CUST_COUNT_ORD/CUST_COUNT_NORMAL ORDRATE --上柜率（%）

SELECT 
	A.CCOM_ID,--地市
	C.COM_NAME,
	A.FLAG,--是否在销
	B.DEPT_COUNT_SALE,--覆盖县级单位数（个）
	B.DEPT_COUNT_NORMAL ,--正常销售区县个数
	B.CUST_COUNT_ORD,--订购客户数（个）
	B.CUST_COUNT_NORMAL  --正常经营零售客户数
FROM 
	(  
	SELECT 
		CCOM_ID,
		CASE WHEN QTY_ORD>0 THEN 1 ELSE 0  END FLAG
	FROM 
		SCMR_SGP_ITEM_MONTH
	WHERE  
		PACK_BAR='26060100' AND MONTH1='201608'
	) A  LEFT JOIN 
	(
		SELECT 
		CCOM_ID,
		DEPT_COUNT_SALE,
		DEPT_COUNT_NORMAL,
		CUST_COUNT_ORD ,
		CUST_COUNT_NORMAL
		FROM SCMR_ITEM_MKT_MONTH
		WHERE DATE1='201608' 
		AND PACK_BAR='26060100'
	)B ON B.CCOM_ID=A.CCOM_ID
	LEFT JOIN ICA_COM C ON A.CCOM_ID=C.COM_ID AND C.ICOM_ID=''
;