--占比:COM_COUNT/SCOUNT ,
--环比增减：(B.QTY_ORD-E.QTY_ORD1)/B.QTY_ORD ,
--订单满足率:QTY_ORD/QTY_NEED
--环比增减:QTY_ORD/QTY_NEED-QTY_ORD1/QTY_NEED1
--订足面:CO_COUNT_ORDFULL/CUST_COUNT_SUPPLY
--断供面:CO_COUNT_NEED-CO_COUNT_ORD)/CO_COUNT_NEED

SELECT 
  A.PACK_BAR,--条形码
  A.ITEM_NAME,--卷烟名称
  B.COM_COUNT1,--在销地市个数
  B.COM_COUNT SCOUNT,--紧俏地市数
  B.QTY_ORD, --商业销量（条）
  B.QTY_NEED, --需求量
  B.CO_COUNT_ORDFULL, --订满户次
  B.CUST_COUNT_SUPPLY ,--投放户数
  B.CO_COUNT_ORD, --订购户次
  B.CO_COUNT_NEED, --有需求户次
  B.QTY_ORD1,  --上一月份商业销量
  B.QTY_NEED1   --上一月份需求量
FROM ICA_ITEM A  
LEFT JOIN 
(
 SELECT 
   PACK_BAR,CCOM_ID,
   SUM(CASE WHEN MONTH1='201608' THEN  QTY_ORD ELSE 0 END ) QTY_ORD,
   SUM(CASE WHEN MONTH1='201608' THEN  QTY_NEED ELSE 0 END ) QTY_NEED,
   SUM(CASE WHEN MONTH1='201608' THEN  CO_COUNT_ORDFULL ELSE 0 END )  CO_COUNT_ORDFULL,
   SUM(CASE WHEN MONTH1='201608' THEN  CUST_COUNT_SUPPLY ELSE 0 END )  CUST_COUNT_SUPPLY,
   SUM(CASE WHEN MONTH1='201608' THEN  CO_COUNT_ORD ELSE 0 END )  CO_COUNT_ORD,
   SUM(CASE WHEN MONTH1='201608' THEN  CO_COUNT_NEED ELSE 0 END )  CO_COUNT_NEED,
   SUM(CASE WHEN MONTH1='201607' THEN  QTY_ORD ELSE 0 END )  QTY_ORD1,
   SUM(CASE WHEN MONTH1='201607' THEN  QTY_NEED ELSE 0 END )  QTY_NEED1,
   SUM(CASE WHEN TACTIC_TYPE='31' THEN 1 ELSE 0  END) COM_COUNT,
   SUM(1) COM_COUNT1
 FROM SCMR_SGP_ITEM_MONTH  
     WHERE   MONTH1 IN ('201608','201607')
     AND PACK_BAR IN('26060100','6901028148603')
     GROUP BY CCOM_ID,PACK_BAR 
)B ON B.PACK_BAR=A.PACK_BAR
;
